export { default as Facilidades } from './Facilidades'
export { default as Produtos } from './Produtos'
export { default as Newsletter } from './Newsletter'
export { default as CategoryBlock } from './CategoryBlock'
export { default as BannerBlock } from './BannerBlock'
